
export const types = [
    { value: 'normal', label: 'Normal' },
    { value: 'fire', label: '🔥Fire' },
    { value: 'water', label: '💧Water' },
    { value: 'grass', label: '🌿Grass' },
    { value: 'poison', label: '💀Poison' },
    { value: 'electric', label: '⚡Electric' },
    { value: 'ice', label: '🧊Ice' },
    { value: 'fighting', label: '🥊Fighting' },
    { value: 'ground', label: '🌱Ground' },
    { value: 'flying', label: '🪽Flying' },
    { value: 'psychic', label: '🔮Psychic' },
    { value: 'bug', label: '🐛Bug' },
    { value: 'rock', label: '🪨Rock' },
    { value: 'ghost', label: '👻Ghost' },
    { value: 'dark', label: '🌑Dark' },
    { value: 'steel', label: '🪧Steel' },
    { value: 'fairy', label: '🧚Fairy' },
    { value: 'dragon', label: '🐉Dragon' },
  ];